name: deploy

on:
  push:
    branches:
      - master
      - staging

jobs:
  deploy:
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_STAGING_APP: ${{ secrets.HEROKU_STAGING_APP }}
      HEROKU_PRODUCTION_APP: ${{ secrets.HEROKU_PRODUCTION_APP }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Deploy Production
        if: github.ref == 'refs/heads/master'
        run: |
          git remote add production https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION_APP.git
          git push -f production origin/master:refs/heads/master

      - name: Deploy Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          git remote add staging https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING_APP.git
          git push -f staging origin/staging:refs/heads/master
